# Generated by Django 5.2.8 on 2026-01-30 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='ظرفیت')),
                ('units', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد واحد')),
                ('day', models.CharField(default='شنبه', max_length=20, verbose_name='روز برگزاری')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='محل برگزاری')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثل نیم\u200cسال اول ۱۴۰۴', max_length=100, unique=True, verbose_name='نام نیم\u200cسال')),
                ('start_selection', models.DateTimeField(verbose_name='شروع انتخاب واحد')),
                ('end_selection', models.DateTimeField(verbose_name='پایان انتخاب واحد')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='UnitLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField(default=12)),
                ('max_units', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name_plural': 'حد واحدهای اخذ شده',
            },
        ),
    ]
