# Generated by Django 5.2.8 on 2025-11-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='ظرفیت')),
                ('units', models.PositiveIntegerField(default=3, verbose_name='تعداد واحد')),
                ('day', models.CharField(default='شنبه', max_length=20, verbose_name='روز برگزاری')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='محل برگزاری')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'role': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.user')),
            ],
        ),
    ]
