# Generated by Django 5.2.8 on 2025-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField(default=12)),
                ('max_units', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name_plural': 'حد واحدهای اخذ شده',
            },
        ),
    ]
