# Generated by Django 5.2.8 on 2026-01-30 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('status', models.CharField(default='در حال بررسی', max_length=20, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='courses.course')),
            ],
        ),
    ]
