# Generated by Django 5.2.8 on 2026-01-30 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseselection',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='selection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='selection.courseselection'),
        ),
        migrations.AlterUniqueTogether(
            name='courseselection',
            unique_together={('student', 'course')},
        ),
    ]
